// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <zcm/zcm_coretypes.h>
#include <zcm/zcm.h>

#ifndef _msg_t_h
#define _msg_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _msg_t msg_t;
struct _msg_t
{
    char*      str;
};

/**
 * Create a deep copy of a msg_t.
 * When no longer needed, destroy it with msg_t_destroy()
 */
msg_t* msg_t_copy(const msg_t* to_copy);

/**
 * Destroy an instance of msg_t created by msg_t_copy()
 */
void msg_t_destroy(msg_t* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _msg_t_subscription_t msg_t_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * msg_t is received.
 */
typedef void(*msg_t_handler_t)(const zcm_recv_buf_t* rbuf,
             const char* channel, const msg_t* msg, void* userdata);

/**
 * Publish a message of type msg_t using ZCM.
 *
 * @param zcm The ZCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means ZCM has transferred
 * responsibility of the message data to the OS.
 */
int msg_t_publish(zcm_t* zcm, const char* channel, const msg_t* msg);

/**
 * Subscribe to messages of type msg_t using ZCM.
 *
 * @param zcm The ZCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by ZCM when a message is received.
 *                This function is invoked by ZCM during calls to zcm_handle() and
 *                zcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return pointer to subscription type, NULL if failure. Must clean up
 *         dynamic memory by passing the pointer to msg_t_unsubscribe.
 */
msg_t_subscription_t* msg_t_subscribe(zcm_t* zcm, const char* channel, msg_t_handler_t handler, void* userdata);

/**
 * Removes and destroys a subscription created by msg_t_subscribe()
 */
int msg_t_unsubscribe(zcm_t* zcm, msg_t_subscription_t* hid);
/**
 * Encode a message of type msg_t into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to msg_t_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int msg_t_encode(void* buf, uint32_t offset, uint32_t maxlen, const msg_t* p);

/**
 * Decode a message of type msg_t from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with msg_t_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int msg_t_decode(const void* buf, uint32_t offset, uint32_t maxlen, msg_t* msg);

/**
 * Release resources allocated by msg_t_decode()
 * @return 0
 */
int msg_t_decode_cleanup(msg_t* p);

/**
 * Check how many bytes are required to encode a message of type msg_t
 */
uint32_t msg_t_encoded_size(const msg_t* p);

// ZCM support functions. Users should not call these
int64_t  __msg_t_get_hash(void);
uint64_t __msg_t_hash_recursive(const __zcm_hash_ptr* p);
int      __msg_t_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const msg_t* p, uint32_t elements);
int      __msg_t_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, msg_t* p, uint32_t elements);
int      __msg_t_decode_array_cleanup(msg_t* p, uint32_t elements);
uint32_t __msg_t_encoded_array_size(const msg_t* p, uint32_t elements);
uint32_t __msg_t_clone_array(const msg_t* p, msg_t* q, uint32_t elements);

#ifdef __cplusplus
}
#endif

#endif
